---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          command: gem install bundler -v 2.1.4
      - run:
          command: bundle install
      - run:
          command: bundle exec rspec
